App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'


urlpatterns = [
    path('', views.blog_list, name='blog_list'),
   
]

App_Login/urls.py
from django.urls import path
from App_Login import views


app_name = 'App_Login'

urlpatterns = [
      path('signup/', views.sign_up,  name='signup'),
      #path('patientsignup/', views.dcmpatient_sign_up,  name='patientsignup'),
      #path('doctorsignup/', views.dcmdoctor_sign_up,  name='doctorsignup'),
      path('login/', views.login_page, name='login'),
      path('logout/', views.logout_user, name='logout'),
      path('profile/', views.profile, name='profile'),
      path('change-profile/', views.user_change, name='user_change'),
      path('password/', views.pass_change, name='pass_change'),
      path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
      path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

Diagnostic_Center_Management02/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('diagnostic_center/', include('Diagnostic_Center.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),
    
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

App_Login/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_dcmpatient = models.BooleanField(default=False)
    is_dcmdoctor = models.BooleanField(default=False)
    profile_pic = models.ImageField(upload_to='profile_pics', null=True, blank=True)
    user_type = models.CharField(max_length=50, null=True, blank=True)

    groups = models.ManyToManyField(
        'auth.Group',
        related_name='user_custom_set',
        blank=True,
        verbose_name='groups',
        help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.',
    )
    
    user_permissions = models.ManyToManyField(
        'auth.Permission',
        related_name='user_custom_set',
        blank=True,
        verbose_name='user permissions',
        help_text='Specific permissions for this user.',
    )

class DcmPatient(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)


    def __str__(self):
    	return self.user.username


class DcmDoctor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    phone=models.CharField(max_length=200)
    designation=models.CharField(max_length=200)


    def __str__(self):
    	return self.user.username


    


App_Login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm, AuthenticationForm
from django.contrib.auth.models import  AbstractUser
from django.db import transaction
from App_Login.models import DcmPatient, User, DcmDoctor


class SignUpForm(UserCreationForm):

    email = forms.EmailField( label="Email Address", required=True)
    
    class Meta:
        model = User
        fields = ('username',  'email', 'password1', 'password2')

class UserProfileChange(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password')

class ProfilePic(forms.ModelForm):
    class Meta:
        model = User
        fields = ['profile_pic']
        

class DcmPatientSignUpForm(UserCreationForm):
    email=forms.EmailField(required=True)
  
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_dcmpatient = True
        user.save()
        patient = DcmPatient.objects.create(user=user)
        return user

class DcmDoctorSignUpForm(UserCreationForm):
    email=forms.EmailField(required=True)
    phone=forms.CharField(required=True)
    desination=forms.CharField(required=True)
  
    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.email=self.cleaned_data.get('email')
        user.is_ = True
        user.save()
        doctor = DcmDoctor.objects.create(user=user)
        doctor.phone=self.cleaned_data.get('phone')
        doctor.desination=self.cleaned_data.get('desination')
        doctor.save()

        return doctor

    
        

App_Login/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import login, authenticate, logout 
from django.shortcuts import HttpResponseRedirect
from django.urls import reverse
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required
from App_Login.forms import SignUpForm, UserProfileChange, ProfilePic, DcmPatientSignUpForm, DcmDoctorSignUpForm
from App_Login.models import User, DcmPatient, DcmDoctor 
# Create your views here.

def sign_up(request):
    form = SignUpForm()
    registered = False
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            registered = True
    dict = {'form': form, 'registered': registered}
    return render(request, 'App_Login/signup.html', context=dict)

class dcmpatient_sign_up(CreateView):
    model = User
    form_class = DcmPatientSignUpForm
    template_name = 'App_Login/patientsignup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'patient'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('index')

class dcmdoctor_sign_up(CreateView):
    model = User
    form_class = DcmDoctorSignUpForm
    template_name = 'App_Login/doctorsignup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'doctor'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        #login(self.request, user)
        return redirect('index')

def login_page(request):
    form = AuthenticationForm()
    if request.method == 'POST':
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            
    dict = {'form': form}
    return render(request, 'App_Login/login.html', context=dict)

@login_required
def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

@login_required
def profile(request):
    return render(request, 'App_Login/profile.html', context={})

@login_required
def user_change(request):
    current_user = request.user
    form = UserProfileChange(instance=current_user)
    if request.method == 'POST':
        form = UserProfileChange(request.POST, instance=current_user)
        if form.is_valid():
            form.save()
            form = UserProfileChange(instance=current_user)
    return render(request, 'App_Login/change_profile.html', context={'form':form})


@login_required
def pass_change(request):
    current_user = request.user
    changed = False
    form = PasswordChangeForm(current_user)
    if request.method == 'POST':
        form = PasswordChangeForm(current_user, data=request.POST)
        if form.is_valid():
            form.save()
            changed = True
    return render(request, 'App_Login/pass_change.html', context={'form':form, 'changed':changed})

@login_required
def add_pro_pic(request):
    form = ProfilePic()
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES)
        if form.is_valid():
            user_obj = form.save(commit=False)
            user_obj.user = request.user
            user_obj.save()
            return  HttpResponseRedirect(reverse('App_Login:profile'))
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})

@login_required
def change_pro_pic(request):
    form = ProfilePic(instance=request.user.user_profile)
    if request.method == 'POST':
        form = ProfilePic(request.POST, request.FILES, instance=request.user.user_profile)
        if request.method == 'POST':
            if form.is_valid():
                form.save()
                return HttpResponseRedirect(reverse('App_Login:profile'))
                
    return render(request, 'App_Login/pro_pic_add.html', context={'form':form})
    

         
    

 
    

templates/App_Login/change_profile.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Profile {% endblock %} 
{% block body_block %}
<form method="POST">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>

{% endblock %}

templates/App_Login/doctorsignup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block title_block %} Create Doctor New Account {% endblock %} 
{% block body_block %} 
{% if registered %}
<div class="alert allert-success">
  Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}
<h2>Create New Account:</h2>
<form method="post">
  {{ form }} 
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br />
<p>Already have an account ? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endif %} 
{% endblock %}

templates/App_Login/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Login {% endblock %}
{% block body_block %}
<h2> Login: </h2>
<form method="POST">
{{form}}
{% csrf_token %}
<button type="submit" class="btn btn-primary btn-sm"> Login </button>
</form>

{% endblock %}

templates/App_Login/pass_change.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block title_block %} Change Password {% endblock %} 
{% block body_block %}
{% if changed %}
<div class="alert alert-success">
    Password change Successfully!
</div>
{% endif %}
<form method="POST">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-warning btn-sm">Change</button>
</form>

{% endblock %}

templates/App_Login/patientsignup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block title_block %} Create Patient New Account {% endblock %} 
{% block body_block %} 
{% if registered %}
<div class="alert allert-success">
  Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}
<h2>Create New Account:</h2>
<form method="post">
  {{ form }} 
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br />
<p>Already have an account ? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endif %} 
{% endblock %}

templates/App_Login/pro_pic_add.html
{% extends 'base.html' %}
{% load crispy_forms_tags %} 
{% block title_block %} Profile {% endblock %} 
{% block body_block %}
<h2>Add Your Profile Picture: </h2>
<form method="post" enctype="multipart/form-data">
<form method="post">
    {{ form }}
    {% csrf_token %}
    <button type="submit" class="btn btn-success btn-sm">Add</button>
</form>

{% endblock %}

templates/App_Login/profile.html
{% extends 'base.html' %} 
{% block title_block %} Profile {% endblock %} 
{% block body_block %}
<h2>Your Profile</h2>
{% if user.user_profile %}
<img src='/media/{{user.user_profile.profile_pic}}' class="rounded-circle" width="100px">
<br>
<br>
<a href="{% url 'App_Login:change_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% else %}
<img src='/media/profile_pics/avatar-male.jpg' class="rounded-circle" width="100px"/>
<br>
<br>
<a href="{% url 'App_Login:add_pro_pic' %}" class="btn btn-info btn-sm">Change Profile Picture</a>
{% endif %}
<br>
<br>
<p>Username: {{ user.username }}</p>
<p>Email: {{ user.email }}</p>
<p>Name: {{user.first_name}} {{ user.last_name }}</p>
<br>
<a href="{% url 'App_Login:user_change' %}" class="btn btn-warning btn-sm">Change Profile Info</a>
{% endblock %}

templates/App_Login/signup.html
{% extends 'base.html' %} 
{% load crispy_forms_tags %}
{% block title_block %} Create New Account {% endblock %} 
{% block body_block %} 
{% if registered %}
<div class="alert allert-success">
  Account Created Successfully! <a href="{% url 'App_Login:login' %}">Login Here</a>
</div>
{% else %}

<h2>Create New Account:</h2>
<form method="post">
  {{ form }} 
  {% csrf_token %}
  <button type="submit" class="btn btn-success btn-sm">Create Account</button>
</form>
<br />
<p>Already have an account ? <a href="{% url 'App_Login:login' %}">Login Here</a></p>
{% endif %} 
{% endblock %}