App_Blog/urls.py
from django.urls import path
from App_Blog import views

app_name = 'App_Blog'


urlpatterns = [
    path('', views.blog_list, name='blog_list'),
   
]

App_Login/urls.py
from django.urls import path
from App_Login import views


app_name = 'App_Login'

urlpatterns = [
      path('signup/', views.sign_up,  name='signup'),
      #path('patientsignup/', views.dcmpatient_sign_up,  name='patientsignup'),
      #path('doctorsignup/', views.dcmdoctor_sign_up,  name='doctorsignup'),
      path('login/', views.login_page, name='login'),
      path('logout/', views.logout_user, name='logout'),
      path('profile/', views.profile, name='profile'),
      path('change-profile/', views.user_change, name='user_change'),
      path('password/', views.pass_change, name='pass_change'),
      path('add-picture/', views.add_pro_pic, name='add_pro_pic'),
      path('change-picture/', views.change_pro_pic, name='change_pro_pic'),
]

Diagnostic_Center/urls.py
from django.urls import path
from Diagnostic_Center import views

app_name = 'Diagnostic_Center'


urlpatterns = [
    path('about/', views.About, name='about'),
    path('view_doctor/', views.View_Doctor, name='view_doctor'),
    path('add_doctor/', views.Add_Doctor, name='add_doctor'),
    #path('delete_doctor(?P<int:pid>)', views.Delete_Doctor, name='delete_doctor'),
    path('view_patient/', views.View_Patient, name='view_patient'),
    path('add_patient/', views.Add_Patient, name='add_patient'),
    #path('delete_patient(?P<int:pid>)', views.Delete_Patient, name='delete_patient'),
    path('view_technician/', views.View_Technician, name='view_technician'),
    path('add_technician/', views.Add_Technician, name='add_technician'),
    #path('delete_technician(?P<int:pid>)', views.Delete_Technician, name='delete_technician'),
]

Diagnostic_Center_Management02/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.conf import settings
from django.contrib.staticfiles.urls import static, staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('App_Login.urls')),
    path('diagnostic_center/', include('Diagnostic_Center.urls')),
    path('blog/', include('App_Blog.urls')),
    path('', views.Index, name='index'),
    
    
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"/>
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>

    <link  rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"/>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.min.css">
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.2/css/buttons.dataTables.min.css">


    <!-- Data Table CDN Start  -->
<script src="https://code.jquery.com/jquery-3.7.0.js"> </script>
<script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.min.js" > </script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/dataTables.buttons.min.js" > </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.10.1/jszip.min.js" > </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js" > </script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js" > </script>
<script src="https://cdn.datatables.net/buttons/2.4.2/js/buttons.html5.min.js"> </script>

<script>
  $(document).ready(function() {
    $('#example').DataTable( {
        dom: 'Bfrtip',
        buttons: [
            'copyHtml5',
            'excelHtml5',
            'csvHtml5',
            'pdfHtml5'
        ]
    } );
} );
</script>
<!-- Data Table CDN END  -->

  <title>{% block title_block %} Diagnostic Center Management {% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
      <ul class="navbar-nav">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}"> <img src="/media/dcmlogo.png" width="50px">Home</a>

        </li>
        {% if user.is_authenticated %}
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbardrop" data-toggle="dropdown">
            @{{user.username}}
          </a>
          <div class="dropdown-menu">

            <a class="dropdown-item" href="{% url 'App_Login:profile' %}">Your Profile</a>
            <hr>
          <a class="dropdown-item" href="{% url 'App_Login:logout' %}">Logout</a>
         
          
        </div>
      </div>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:signup' %}">SignUp</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:patientsignup' %}">Create Patient </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:doctorsignup' %}">Create Doctor </a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'App_Login:login' %}">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Diagnostic_Center:about' %}">About Us</a>
        </li>
       
        {% endif %}
        {% if request.user.is_staff %}
        
    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Doctor</a>
      <div class="dropdown-menu">
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:add_doctor' %}">Add Doctor</a>
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_doctor' %}">View Doctor</a>
      </div>
    </li>
    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Patient</a>
      <div class="dropdown-menu">
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:add_patient' %}">Add Patient</a>
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_patient' %}">View Patient</a>
      </div>
    </li>
    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Appointment</a>
      <div class="dropdown-menu">
        <a class="dropdown-item"  href="#">Add Appointment</a>
        <a class="dropdown-item"  href="#">View Appointment</a>
      </div>
    </li>
    <li class="nav-item dropdown"><a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#">Technician</a>
      <div class="dropdown-menu">
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:add_technician' %}">Add Technician</a>
        <a class="dropdown-item"  href="{% url 'Diagnostic_Center:view_technician' %}">View Technician</a>
      </div>
    </li>
    {% endif %}

      </ul>
    </nav>
    <div class="container" style="padding-top: 20px">
      {% block body_block %} 
      {% endblock %}
    </div>
  </body>
</html>